### ISSUE TITLE
Bytestring error

### ISSUE THREAD

**Issue by anufry** [ViktorStiskala/django-shared-session#6]
Hello

Thank you for your solution, but it was not working for me until I had added this (**.decode('utf-8')**) here:

```
def get_message(self, request, domain):
        return urlsafe_base64_encode(self.encrypt_payload({
            'key': request.session.session_key,
            'src': request.META['HTTP_HOST'],
            'dst': domain,
            'ts': timezone.now().isoformat()
        })).decode('utf-8')
```

It generates bad JS filename otherwise (like this):

> http://domain.local:8002/shared-session/b'iNxpGciyEzerxC-Dqd_BPijpYFnrWqrMNuKSodR4J1r3zDtAbzRrDDb-tdD07nG3Xcj6jXPH1qlGVpymG1zBQMMSex6G6ILgs240Exe3vYeOhixsKgwfZr1fykXXb9g-yaEohlhTRGG6AbiFH3Zm7dwhSL93BZTMbyoi0M6uKEVA3qIePkYoYGNqItDNTXG5NmdZhTdTe25fPwHAldTqUWOgYDS4G_Lhzwzd7HcGpQplwkpNAzgqqQ'.js

Python 3.6, django 2.1

Can you fix it please (if it is the bug) or tell me how to fix it without changing your code in my venv?

Thanks a lot!

**Comment by ViktorStiskala** [comment]
Thanks for pointing it out. I haven't been using Django 2.x yet, so I didn't notice the problem.

Please upgrade to the latest version using pip.
